#pragma once

#include "screen_9bit_packet.hh"

namespace mdrivlib::ST7701S
{

static constexpr mdrivlib::Screen9BitPacket InitCmds[] = {
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x13},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xEF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x10},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xC0},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xC1},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0E},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0C},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xC2},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x07},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x02},

	// toysynth:
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xC3},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x02}, //0x80 = DE off, 0x02 = invert pixel clock
	{.action = Screen9BitPacket::Type::Data, .payload = 0},	   // HBP
	{.action = Screen9BitPacket::Type::Data, .payload = 0},	   // VBP

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xCC},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x30},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB0},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x17},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x1F},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0E},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x11},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x06},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0D},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x07},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x26},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x03},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x11},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0F},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x2A},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x31},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x1C},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB1},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x17},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x1F},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0D},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x11},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x07},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x26},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x04},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x11},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0F},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x2A},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x31},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x1C},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x11},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB0},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x5C},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB1},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x68},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB2},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x85},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB3},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x80},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB5},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x49},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB7},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x87},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB8},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x22},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xB9},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x10},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x1F},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xBB},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x03},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xC1},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x88},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xC2},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x88},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xD0},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x88},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE0},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x02},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0C},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE1},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x03},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x05},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x02},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x04},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE2},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x03},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x03},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x02},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x02},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE3},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x33},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x33},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE4},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE5},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0B},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD4},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0D},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD6},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x07},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD0},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x09},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD2},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE6},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x33},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x33},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE7},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE8},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0A},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD5},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD7},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x06},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD1},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xD3},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xEB},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xE4},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xE4},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xED},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x45},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x67},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xFC},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x3F},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xAB},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xBA},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xF3},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x10},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xCF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x76},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x54},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xEF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x10},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0D},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x04},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x3F},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x1F},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x13},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE8},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0E},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE8},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x0C},
	{.action = Screen9BitPacket::Type::DelayMS, .payload = 20},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xE8},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x40},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0x3A},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x60},

	// MADCTL
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0x36},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00}, //0x10 = reverse scan, 0x00 = not reverse

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0x51},
	{.action = Screen9BitPacket::Type::Data, .payload = 0xFF},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0x35},
	{.action = Screen9BitPacket::Type::Data, .payload = 0x00},

	{.action = Screen9BitPacket::Type::Cmd, .payload = 0x11},
	{.action = Screen9BitPacket::Type::DelayMS, .payload = 120},
	{.action = Screen9BitPacket::Type::Cmd, .payload = 0x29},

};

} // namespace mdrivlib::ST7701S
