#pragma once

#include "screen_9bit_setup.hh"

namespace mdrivlib::ST7701S
{

static constexpr mdrivlib::Screen9BitPacket InitCmds[] = {
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xFF},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x01}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x13},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xEF},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xFF},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x01}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x10},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xC0},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x77},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xC1},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0E}, {.type = Screen9BitPacket::Type::Data, .payload = 0x0C},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xC2},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x07},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x02}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xCC},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x30}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB0},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x17},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x1F}, {.type = Screen9BitPacket::Type::Data, .payload = 0x0E},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x11}, {.type = Screen9BitPacket::Type::Data, .payload = 0x06},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0D}, {.type = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x07}, {.type = Screen9BitPacket::Type::Data, .payload = 0x26},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x03}, {.type = Screen9BitPacket::Type::Data, .payload = 0x11},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0F}, {.type = Screen9BitPacket::Type::Data, .payload = 0x2A},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x31}, {.type = Screen9BitPacket::Type::Data, .payload = 0x1C},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xB1},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x17}, {.type = Screen9BitPacket::Type::Data, .payload = 0x1F},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0D}, {.type = Screen9BitPacket::Type::Data, .payload = 0x11},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x07}, {.type = Screen9BitPacket::Type::Data, .payload = 0x0C},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x08}, {.type = Screen9BitPacket::Type::Data, .payload = 0x08},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x26}, {.type = Screen9BitPacket::Type::Data, .payload = 0x04},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x11}, {.type = Screen9BitPacket::Type::Data, .payload = 0x0F},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x2A}, {.type = Screen9BitPacket::Type::Data, .payload = 0x31},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x1C}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x77}, {.type = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x11}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB0},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x5C}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB1},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x68}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB2},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x85}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB3},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x80}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB5},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x49}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB7},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x87}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB8},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x22}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xB9},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x10}, {.type = Screen9BitPacket::Type::Data, .payload = 0x1F},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xBB},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x03},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xC1},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x88},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xC2},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x88},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xD0},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x88},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xE0},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x02},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0C}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xE1},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x03}, {.type = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x05}, {.type = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x02}, {.type = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x04}, {.type = Screen9BitPacket::Type::Data, .payload = 0x96},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x44}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xE2},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x03}, {.type = Screen9BitPacket::Type::Data, .payload = 0x03},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x02}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x02}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xE3},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x33},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x33}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xE4},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x44}, {.type = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xE5},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x0B},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xD4}, {.type = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x8C}, {.type = Screen9BitPacket::Type::Data, .payload = 0x0D},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xD6}, {.type = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x8C}, {.type = Screen9BitPacket::Type::Data, .payload = 0x07},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xD0}, {.type = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x8C}, {.type = Screen9BitPacket::Type::Data, .payload = 0x09},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xD2}, {.type = Screen9BitPacket::Type::Data, .payload = 0x28},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x8C}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xE6},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x33}, {.type = Screen9BitPacket::Type::Data, .payload = 0x33},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xE7},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x44}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xE8},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0A}, {.type = Screen9BitPacket::Type::Data, .payload = 0xD5},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x28}, {.type = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0C}, {.type = Screen9BitPacket::Type::Data, .payload = 0xD7},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x28}, {.type = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x06}, {.type = Screen9BitPacket::Type::Data, .payload = 0xD1},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x28}, {.type = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x08}, {.type = Screen9BitPacket::Type::Data, .payload = 0xD3},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x28}, {.type = Screen9BitPacket::Type::Data, .payload = 0x8C},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xEB},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x01}, {.type = Screen9BitPacket::Type::Data, .payload = 0xE4},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xE4}, {.type = Screen9BitPacket::Type::Data, .payload = 0x44},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xED},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xFF}, {.type = Screen9BitPacket::Type::Data, .payload = 0x45},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x67}, {.type = Screen9BitPacket::Type::Data, .payload = 0xFC},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x01}, {.type = Screen9BitPacket::Type::Data, .payload = 0x3F},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xAB}, {.type = Screen9BitPacket::Type::Data, .payload = 0xFF},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xFF}, {.type = Screen9BitPacket::Type::Data, .payload = 0xBA},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xF3}, {.type = Screen9BitPacket::Type::Data, .payload = 0x10},
	{.type = Screen9BitPacket::Type::Data, .payload = 0xCF}, {.type = Screen9BitPacket::Type::Data, .payload = 0x76},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x54}, {.type = Screen9BitPacket::Type::Data, .payload = 0xFF},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xEF},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x10},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0D}, {.type = Screen9BitPacket::Type::Data, .payload = 0x04},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x08}, {.type = Screen9BitPacket::Type::Data, .payload = 0x3F},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x1F}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x77}, {.type = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x13}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xE8},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x0E},

	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xE8},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x0C}, {.type = Screen9BitPacket::Type::DelayMS, .payload = 20},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0xE8},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x40},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Cmd, .payload = 0xFF},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x77}, {.type = Screen9BitPacket::Type::Data, .payload = 0x01},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00}, {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Data, .payload = 0x00},

	{.type = Screen9BitPacket::Type::Cmd, .payload = 0x3A},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x60},

	{.type = Screen9BitPacket::Type::Cmd, .payload = 0x36},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x00},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0x35},	 {.type = Screen9BitPacket::Type::Data, .payload = 0x00},

	{.type = Screen9BitPacket::Type::Cmd, .payload = 0x11},	 {.type = Screen9BitPacket::Type::DelayMS, .payload = 120},
	{.type = Screen9BitPacket::Type::Cmd, .payload = 0x29},

};

} // namespace mdrivlib::ST7701S
